/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Funciones.TableModel;
import Funciones.aEstudiante;
import Funciones.fBuscarEstudiantes;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static ventanas.FrmInicio.Escritorio;
import static ventanas.FrmInicio.dupl;
import static ventanas.FrmInicio.usuario;

/**
 *
 * @author jalex
 */
public class Consultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form formularioempleado
     */
    int cont = 3;
    String salida = "";
    static String numdoc = "";

    public Consultas() {
        try {
            initComponents();

            Color myColor = new Color(197, 242, 254);
            tblEstudiantes.setBackground(myColor);
            ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            this.setSize(620, 540);
            cargarEstudiantes();
            //this.setLocationRelativeTo(null);
        } catch (Exception ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void cargarEstudiantes() throws Exception {

        fBuscarEstudiantes objBD = new fBuscarEstudiantes();
        List<aEstudiante> lstTempMed = objBD.buscarEstudiantes(new aEstudiante(), cont, salida);
        TableModel objModelo = new TableModel(lstTempMed);
        tblEstudiantes.setModel(objModelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jLabelEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        cmbConsulta = new javax.swing.JComboBox<>();
        jButtBuscar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLabelfondo1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/TrianTrans.png"));
        Image conversion = imagen.getImage();
        Image tamanio = conversion.getScaledInstance(190, 100, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(tamanio);
        lblLogo.setIcon(icon);
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 190, 150));

        jLabelEmpleado.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabelEmpleado.setForeground(new java.awt.Color(0, 102, 153));
        jLabelEmpleado.setText("Consulta");
        getContentPane().add(jLabelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        tblEstudiantes.setAutoCreateRowSorter(true);
        tblEstudiantes.setBackground(new java.awt.Color(153, 255, 255));
        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEstudiantes.setFillsViewportHeight(true);
        tblEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstudiantes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 580, 300));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 140, 25));

        cmbConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Documento", "Nombre" }));
        cmbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 110, 25));

        jButtBuscar.setBackground(new java.awt.Color(153, 204, 255));
        jButtBuscar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButtBuscar.setText("Buscar");
        jButtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 90, -1));

        jBsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/closei.png"))); // NOI18N
        jBsalir.setBorder(null);
        jBsalir.setBorderPainted(false);
        jBsalir.setContentAreaFilled(false);
        jBsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 8, 30, 20));

        jLabelfondo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abstracto-azul.jpg"))); // NOI18N
        jLabelfondo1.setText("jLabel1");
        jLabelfondo1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new javax.swing.ImageIcon(getClass().getResource("/imagenes/blakw.png")))); // NOI18N
        getContentPane().add(jLabelfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudiantesMouseClicked

        if (evt.getClickCount() >= 2) {
            int indice = tblEstudiantes.getSelectedRow();
            aEstudiante dts = new aEstudiante();
            dts.setIdEstudiante((Integer) tblEstudiantes.getValueAt(indice, 0));
            dts.setNomEstudiante((String) tblEstudiantes.getValueAt(indice, 1));
            dts.setApllEstudiante((String) tblEstudiantes.getValueAt(indice, 2));
            dts.setNumDocumento((String) tblEstudiantes.getValueAt(indice, 3));

            int ax = JOptionPane.showConfirmDialog(null, "desea modificar los datos" + dts.getNomEstudiante() + dts.getNumDocumento(),
                    " confirmar ", JOptionPane.OK_CANCEL_OPTION);
            numdoc = dts.getNumDocumento().trim();

            if (ax == JOptionPane.OK_OPTION) {
                System.out.println(usuario);
                Formestu form = new Formestu();
                Escritorio.add(form);
                Dimension desktopSize = Escritorio.getSize();
                Dimension FrameSize = form.getSize();
                form.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
                form.show();
                form.setVisible(rootPaneCheckingEnabled);
                // Formestu.jTextFieldCodigo.setText(dts.getNumDocumento());
                this.setVisible(false);
            }

        }

    }//GEN-LAST:event_tblEstudiantesMouseClicked

    private void jButtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBuscarActionPerformed
        try {
            cont = cmbConsulta.getSelectedIndex();
            salida = txtBuscar.getText();
            cargarEstudiantes();

        } catch (Exception ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtBuscarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        dupl = 0;

    }//GEN-LAST:event_formInternalFrameClosed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void cmbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConsultaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        dupl = 1;
    }//GEN-LAST:event_formInternalFrameOpened

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbConsulta;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jButtBuscar;
    private javax.swing.JLabel jLabelEmpleado;
    private javax.swing.JLabel jLabelfondo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void inhabilitar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
