/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Funciones.Conexion;
import Funciones.Fnotas;
import Funciones.aNotas;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static ventanas.FrmInicio.Escritorio;
import static ventanas.FrmInicio.dupl;

/**
 *
 * @author jeison.zapata
 */
public final class Formnotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form formulariorequerimiento
     */
    public Formnotas() {

        initComponents();
        String ciclo = JTciclo.getText();
        jLnombre1.setText("NOMBRE: " + Formestu.nombre + " " + Formestu.apellido);
        jLIdEstudiante.setText("CODIGO: " + Formestu.idestudiante);
        this.setSize(641, 433);
        inhabilitar();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        aNotas dts = new aNotas();
        Fnotas fun = new Fnotas();
        int matria = 0;
        if (Formmtric.cicl.equals("Basico")) {
            matria = 1;
        } else {
            matria = 7;
        }

        int idmtr = Formmtric.IdMatricula;
        String idst = Formestu.idestudiante;

        fun.mostrar(dts, idst + " and IdMatricula = " + idmtr + " and IdMateria = " + matria);
        if (dts.getNotaFinal() != null) {
            jCNotas1.setSelectedItem(dts.getNotaFinal());
            jCNotas1.setEnabled(false);
            deshabilita();

        }

        matria++;
        fun.mostrar(dts, idst + " and IdMatricula = " + idmtr + " and IdMateria = " + matria);
        if (dts.getNotaFinal() != null) {
            jCNotas2.setSelectedItem(dts.getNotaFinal());
            jCNotas2.setEnabled(false);
            deshabilita();;
        }

        matria++;
        fun.mostrar(dts, idst + " and IdMatricula = " + idmtr + " and IdMateria = " + matria);
        if (dts.getNotaFinal() != null) {
            jCNotas3.setSelectedItem(dts.getNotaFinal());
            jCNotas3.setEnabled(false);
            deshabilita();
        }

        matria++;
        fun.mostrar(dts, idst + " and IdMatricula = " + idmtr + " and IdMateria = " + matria);
        if (dts.getNotaFinal() != null) {
            jCNotas4.setSelectedItem(dts.getNotaFinal());
            jCNotas4.setEnabled(false);
            deshabilita();
        }

        matria++;
        fun.mostrar(dts, idst + " and IdMatricula = " + idmtr + " and IdMateria = " + matria);
        if (dts.getNotaFinal() != null) {
            jCNotas5.setSelectedItem(dts.getNotaFinal());
            jCNotas5.setEnabled(false);
            deshabilita();
        }

        matria++;
        fun.mostrar(dts, idst + " and IdMatricula = " + idmtr + " and IdMateria = " + matria);
        if (dts.getNotaFinal() != null) {
            jCNotas6.setSelectedItem(dts.getNotaFinal());
            jCNotas6.setEnabled(false);
            deshabilita();
        }
        if (jCNotas1.getSelectedIndex() != -1 && jCNotas2.getSelectedIndex() != -1
                && jCNotas3.getSelectedIndex() != -1 && jCNotas4.getSelectedIndex() != -1
                && jCNotas5.getSelectedIndex() != -1 && jCNotas6.getSelectedIndex() != -1) {
            jBNext.setEnabled(true);
            deshabilita();
        }

    }

    public static String aprobar = "";
    public static int aprobo = 0;
    int idmater;
    int contador = 1;

    void inhabilitar() {
        jCNotas1.setSelectedIndex(-1);
        jCNotas2.setSelectedIndex(-1);
        jCNotas3.setSelectedIndex(-1);
        jCNotas4.setSelectedIndex(-1);
        jCNotas5.setSelectedIndex(-1);
        jCNotas6.setSelectedIndex(-1);
        jButAgre.setEnabled(false);
        jBNext.setEnabled(false);

    }

    void habilitar() {
        jCNotas3.setEnabled(true);

    }

    void deshabilita() {
        jButAgre.setEnabled(false);
        jBNext.setEnabled(true);

    }

    public void validan() {
        if (jCNotas1.getSelectedIndex() != -1 && jCNotas2.getSelectedIndex() != -1
                && jCNotas3.getSelectedIndex() != -1 && jCNotas4.getSelectedIndex() != -1
                && jCNotas5.getSelectedIndex() != -1 && jCNotas6.getSelectedIndex() != -1) {
            jButAgre.setEnabled(true);

        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelnotas_estudiantes = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jButAgre = new javax.swing.JButton();
        jButtonEditar2 = new javax.swing.JButton();
        jBNext = new javax.swing.JButton();
        jLblNomb = new javax.swing.JLabel();
        jLblNotas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLaMat1 = new javax.swing.JLabel();
        jCNotas1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLaMat2 = new javax.swing.JLabel();
        jCNotas2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLaMat3 = new javax.swing.JLabel();
        jCNotas3 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLaMat5 = new javax.swing.JLabel();
        jCNotas5 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLaMat4 = new javax.swing.JLabel();
        jCNotas4 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLaMat6 = new javax.swing.JLabel();
        jCNotas6 = new javax.swing.JComboBox<>();
        jpNotas = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLCiclo = new javax.swing.JLabel();
        jLIdEstudiante = new javax.swing.JLabel();
        jLAnio = new javax.swing.JLabel();
        jLSemestre = new javax.swing.JLabel();
        jLJornada = new javax.swing.JLabel();
        jLnombre1 = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jLabelFondoActualizar = new javax.swing.JLabel();
        JTciclo = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelnotas_estudiantes.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabelnotas_estudiantes.setForeground(new java.awt.Color(0, 102, 153));
        jLabelnotas_estudiantes.setText("REGISTRO DE NOTAS ");
        getContentPane().add(jLabelnotas_estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLnombre.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLnombre.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 20, 40));

        jButAgre.setBackground(new java.awt.Color(0, 0, 0));
        jButAgre.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButAgre.setForeground(new java.awt.Color(255, 255, 255));
        jButAgre.setText("AGREGAR");
        jButAgre.setEnabled(false);
        jButAgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAgreActionPerformed(evt);
            }
        });
        getContentPane().add(jButAgre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 100, -1));

        jButtonEditar2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEditar2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButtonEditar2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar2.setText("Volver");
        jButtonEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 90, -1));

        jBNext.setBackground(new java.awt.Color(0, 0, 0));
        jBNext.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jBNext.setForeground(new java.awt.Color(255, 255, 255));
        jBNext.setText("Continuar");
        jBNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNextActionPerformed(evt);
            }
        });
        getContentPane().add(jBNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 88, 30));

        jLblNomb.setBackground(new java.awt.Color(164, 234, 252));
        jLblNomb.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLblNomb.setText("DATOS");
        jLblNomb.setFocusable(false);
        jLblNomb.setOpaque(true);
        jLblNomb.setRequestFocusEnabled(false);
        jLblNomb.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLblNomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLblNotas.setBackground(new java.awt.Color(164, 234, 252));
        jLblNotas.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLblNotas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLblNotas.setText("NOTAS");
        jLblNotas.setFocusable(false);
        jLblNotas.setOpaque(true);
        getContentPane().add(jLblNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLaMat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLaMat1.setText("Materia 1");
        jPanel1.add(jLaMat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 22));

        jCNotas1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jCNotas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bajo", "Basico", "Alto", "Superior" }));
        jCNotas1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCNotas1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCNotas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 2, 100, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 270, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLaMat2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLaMat2.setText("Materia 1");
        jPanel2.add(jLaMat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 22));

        jCNotas2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jCNotas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bajo", "Basico", "Alto", "Superior" }));
        jCNotas2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCNotas1ItemStateChanged(evt);
            }
        });
        jPanel2.add(jCNotas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 2, 100, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 252, 270, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLaMat3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLaMat3.setText("Materia 1");
        jPanel3.add(jLaMat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 22));

        jCNotas3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jCNotas3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bajo", "Basico", "Alto", "Superior" }));
        jCNotas3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCNotas1ItemStateChanged(evt);
            }
        });
        jPanel3.add(jCNotas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 2, 100, 25));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 284, 270, 30));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLaMat5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLaMat5.setText("Materia 1");
        jPanel5.add(jLaMat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 22));

        jCNotas5.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jCNotas5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bajo", "Basico", "Alto", "Superior" }));
        jCNotas5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCNotas1ItemStateChanged(evt);
            }
        });
        jCNotas5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNotas5ActionPerformed(evt);
            }
        });
        jPanel5.add(jCNotas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 2, 100, 25));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 252, 270, 30));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLaMat4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLaMat4.setText("Materia 1");
        jPanel4.add(jLaMat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 22));

        jCNotas4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jCNotas4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bajo", "Basico", "Alto", "Superior" }));
        jCNotas4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCNotas1ItemStateChanged(evt);
            }
        });
        jPanel4.add(jCNotas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 2, 100, 25));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 220, 270, 30));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLaMat6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLaMat6.setText("Materia 1");
        jPanel6.add(jLaMat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 22));

        jCNotas6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jCNotas6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bajo", "Basico", "Alto", "Superior" }));
        jCNotas6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCNotas1ItemStateChanged(evt);
            }
        });
        jCNotas6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNotas6ActionPerformed(evt);
            }
        });
        jPanel6.add(jCNotas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 2, 100, 25));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 284, 270, 30));

        jpNotas.setBackground(new java.awt.Color(164, 234, 252));
        jpNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jpNotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jpNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 560, 110));

        jPanel7.setBackground(new java.awt.Color(164, 234, 252));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCiclo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLCiclo.setText("CICLO:");
        jPanel7.add(jLCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 180, 25));

        jLIdEstudiante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLIdEstudiante.setText("CODIGO:");
        jPanel7.add(jLIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 25));

        jLAnio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLAnio.setText("AÑO:");
        jPanel7.add(jLAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 100, 25));

        jLSemestre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSemestre.setText("SEMESTRE:");
        jPanel7.add(jLSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 100, 25));

        jLJornada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLJornada.setText("JORNADA:");
        jPanel7.add(jLJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 170, 25));

        jLnombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLnombre1.setForeground(new java.awt.Color(0, 0, 51));
        jLnombre1.setText("NOMBRE:");
        jPanel7.add(jLnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 230, 25));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 560, 100));

        jBsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/closei.png"))); // NOI18N
        jBsalir.setBorder(null);
        jBsalir.setBorderPainted(false);
        jBsalir.setContentAreaFilled(false);
        jBsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 20));

        jLabelFondoActualizar.setForeground(new java.awt.Color(0, 102, 0));
        jLabelFondoActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abstracto-azul.jpg"))); // NOI18N
        jLabelFondoActualizar.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new javax.swing.ImageIcon(getClass().getResource("/imagenes/blakw.png")))); // NOI18N
        getContentPane().add(jLabelFondoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));
        getContentPane().add(JTciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 10, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButAgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAgreActionPerformed

        aNotas dts = new aNotas();
        Fnotas fun = new Fnotas();

        String ciclo = JTciclo.getText();
        if (ciclo.equals("1")) {
            idmater = 1;
        } else {
            idmater = 7;
        }

        dts.setIdEstudiante(Integer.parseInt(Formestu.idestudiante));
        dts.setIdMaterias(idmater);
        dts.setIdMatricula(Formmtric.IdMatricula);
        dts.setMaterias(jLaMat1.getText().trim());
        dts.setNotaFinal(jCNotas1.getSelectedItem().toString().trim());
        fun.insertar(dts);
        idmater++;

        dts.setIdEstudiante(Integer.parseInt(Formestu.idestudiante));
        dts.setIdMaterias(idmater);
        dts.setIdMatricula(Formmtric.IdMatricula);
        dts.setMaterias(jLaMat2.getText().trim());
        dts.setNotaFinal(jCNotas2.getSelectedItem().toString().trim());
        fun.insertar(dts);
        idmater++;

        dts.setIdEstudiante(Integer.parseInt(Formestu.idestudiante));
        dts.setIdMaterias(idmater);
        dts.setIdMatricula(Formmtric.IdMatricula);
        dts.setMaterias(jLaMat3.getText().trim());
        dts.setNotaFinal(jCNotas3.getSelectedItem().toString().trim());
        fun.insertar(dts);
        idmater++;

        dts.setIdEstudiante(Integer.parseInt(Formestu.idestudiante));
        dts.setIdMaterias(idmater);
        dts.setIdMatricula(Formmtric.IdMatricula);
        dts.setMaterias(jLaMat4.getText().trim());
        dts.setNotaFinal(jCNotas4.getSelectedItem().toString().trim());
        fun.insertar(dts);
        idmater++;

        dts.setIdEstudiante(Integer.parseInt(Formestu.idestudiante));
        dts.setIdMaterias(idmater);
        dts.setIdMatricula(Formmtric.IdMatricula);
        dts.setMaterias(jLaMat5.getText().trim());
        dts.setNotaFinal(jCNotas5.getSelectedItem().toString().trim());
        fun.insertar(dts);
        idmater++;

        dts.setIdEstudiante(Integer.parseInt(Formestu.idestudiante));
        dts.setIdMaterias(idmater);
        dts.setIdMatricula(Formmtric.IdMatricula);
        dts.setMaterias(jLaMat6.getText().trim());
        dts.setNotaFinal(jCNotas6.getSelectedItem().toString().trim());
        if (fun.insertar(dts)) {
            JOptionPane.showMessageDialog(null, "Nota de registrada con exito");
        }

        jBNext.setEnabled(true);
        jButAgre.setEnabled(false);

    }//GEN-LAST:event_jButAgreActionPerformed

    private void jBNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNextActionPerformed

        aNotas dts = new aNotas();
        Fnotas func = new Fnotas();
        Conexion cn = new Conexion();

        String sSQL = "Select * from NotaEstudiantes where IdEstudiante = ?";
        try {

            PreparedStatement pst = cn.obtener().prepareStatement(sSQL);
            pst.setString(1, Formestu.idestudiante);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {

                dts.setIdMaterias(rs.getInt("IdMateria"));
                dts.setMaterias(rs.getString("Materia"));
                dts.setNotaFinal(rs.getString("NotaFinal"));

                if (rs.getString("NotaFinal").trim().equals("Bajo")) {
                    aprobo = +1;
                }
            }

            if (aprobo == 0) {
                aprobar = "Aprobado";
            } else {
                aprobar = "No aprobado";
            }
        } catch (Exception er) {
            System.out.println("" + er);
        }

        Formcertifi form = null;
        try {
            form = new Formcertifi();
        } catch (Exception ex) {
            Logger.getLogger(Formnotas.class.getName()).log(Level.SEVERE, null, ex);
        }
        Escritorio.add(form);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = form.getSize();
        form.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        form.show();
        this.setVisible(false);


    }//GEN-LAST:event_jBNextActionPerformed

    private void jButtonEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditar2ActionPerformed
        Formmtric form = new Formmtric();
        Escritorio.add(form);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = form.getSize();
        form.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        form.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEditar2ActionPerformed

    private void jCNotas5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNotas5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCNotas5ActionPerformed

    private void jCNotas6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNotas6ActionPerformed

    }//GEN-LAST:event_jCNotas6ActionPerformed

    private void jCNotas1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCNotas1ItemStateChanged
        validan();
    }//GEN-LAST:event_jCNotas1ItemStateChanged

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        dupl = 0;
    }//GEN-LAST:event_formInternalFrameClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formnotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formnotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField JTciclo;
    private javax.swing.JButton jBNext;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jButAgre;
    private javax.swing.JButton jButtonEditar2;
    public static javax.swing.JComboBox<String> jCNotas1;
    public static javax.swing.JComboBox<String> jCNotas2;
    public static javax.swing.JComboBox<String> jCNotas3;
    public static javax.swing.JComboBox<String> jCNotas4;
    public static javax.swing.JComboBox<String> jCNotas5;
    public static javax.swing.JComboBox<String> jCNotas6;
    public static javax.swing.JLabel jLAnio;
    public static javax.swing.JLabel jLCiclo;
    public static javax.swing.JLabel jLIdEstudiante;
    public static javax.swing.JLabel jLJornada;
    public static javax.swing.JLabel jLSemestre;
    public static javax.swing.JLabel jLaMat1;
    public static javax.swing.JLabel jLaMat2;
    public static javax.swing.JLabel jLaMat3;
    public static javax.swing.JLabel jLaMat4;
    public static javax.swing.JLabel jLaMat5;
    public static javax.swing.JLabel jLaMat6;
    private javax.swing.JLabel jLabelFondoActualizar;
    private javax.swing.JLabel jLabelnotas_estudiantes;
    private javax.swing.JLabel jLblNomb;
    private javax.swing.JLabel jLblNotas;
    public static javax.swing.JLabel jLnombre;
    public static javax.swing.JLabel jLnombre1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jpNotas;
    // End of variables declaration//GEN-END:variables
}
