/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Funciones.Fmatriculas;
import Funciones.aMatriculas;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static ventanas.FrmInicio.Escritorio;
import static ventanas.FrmInicio.dupl;

/**
 *
 * @author jeison.zapata
 */
public class Formmtric extends javax.swing.JInternalFrame {

    public Formmtric() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setSize(459, 304);
        jLnombre.setText(Formestu.nombre + " " + Formestu.apellido);
        jLIdEstudiant.setText("CODIGO: " + Formestu.idestudiante);
        jBNext.setEnabled(false);
        jBAgregar4.setEnabled(false);

        aMatriculas dts = new aMatriculas();
        Fmatriculas func = new Fmatriculas();
        func.Mostrar(dts);
        jCJornada.setEnabled(false);
        jCCiclo.setEnabled(false);
        if (dts.getAniomatr() != (null)) {
            jBNext.setEnabled(true);
            jCAnioMtr.setSelectedItem(dts.getAniomatr());
            jCSemestre.setSelectedItem(dts.getSemestre());
            jCJornada.setSelectedItem(dts.getJornada());
            jCCiclo.setSelectedItem(dts.getCiclo());
            jBNext.setEnabled(true);
            jBNext.requestFocus();
        }
    }

    public static String anio = "";
    public static String semes = "";
    public static String jornada = "";
    public static String cicl = "";
    public static int IdMatricula = 0;
    private String accion = "guardar";

    void Limpiar() {
        //limpiar cajas de texto 
        jCJornada.setSelectedIndex(-1);
        jCCiclo.setSelectedIndex(-1);
        jTIdEstudiante.setEnabled(false);
    }

    void Deshabilitar() {
        // Deshabilita cajas de texto 
        jBAgregar4.setEnabled(false);
        jBEditar.setEnabled(false);
        jCAnioMtr.setEnabled(false);
        jCSemestre.setEnabled(false);
        jCJornada.setEnabled(false);
        jCCiclo.setEnabled(false);

    }

    public void validar() {
        jBNext.setEnabled(false);
        if (jCAnioMtr.getSelectedIndex() != -1
                && jCCiclo.getSelectedIndex() != -1
                && jCJornada.getSelectedIndex() != -1
                && jCSemestre.getSelectedIndex() != -1) {
            jBAgregar4.setEnabled(false);
            jBNext.setEnabled(true);
            jCJornada.setEnabled(false);
            jCCiclo.setEnabled(false);
        } else if (jCAnioMtr.getSelectedIndex() != -1
                && jCSemestre.getSelectedIndex() != -1) {
            //jBAgregar4.setEnabled(true);
            jCJornada.setEnabled(true);
            jCCiclo.setEnabled(true);
        }

    }

    public void check() {

        aMatriculas dts = new aMatriculas();
        Fmatriculas func = new Fmatriculas();
        jBAgregar4.setEnabled(false);

        anio = jCAnioMtr.getSelectedItem().toString();
        switch (jCSemestre.getSelectedIndex()) {
            case 0:
                semes = "1";
                break;
            case 1:
                semes = "2";
                break;
            default:
                semes = "null";
                break;
        }
        func.consultamtr(dts, anio, semes);
        jCJornada.setSelectedItem(dts.getJornada());
        jCCiclo.setSelectedItem(dts.getCiclo());

        if (dts.getCiclo() != (null)) {
            jBAgregar4.setEnabled(true);
            jCJornada.setSelectedItem(dts.getJornada());
            jCCiclo.setSelectedItem(dts.getCiclo());
        }
        validar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEmpleado = new javax.swing.JLabel();
        jLSemestre = new javax.swing.JLabel();
        jLabelanio = new javax.swing.JLabel();
        jLCliclo = new javax.swing.JLabel();
        jLabeljornada = new javax.swing.JLabel();
        jCCiclo = new javax.swing.JComboBox<>();
        jLnombre = new javax.swing.JLabel();
        jBAgregar4 = new javax.swing.JButton();
        jCSemestre = new javax.swing.JComboBox<>();
        jBEditar = new javax.swing.JButton();
        jCAnioMtr = new javax.swing.JComboBox<>();
        jCJornada = new javax.swing.JComboBox<>();
        jBNext = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLfondo = new javax.swing.JLabel();
        jLIdEstudiant = new javax.swing.JLabel();
        jTIdEstudiante = new javax.swing.JTextField();
        JIdestudiante = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Matricula");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEmpleado.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabelEmpleado.setForeground(new java.awt.Color(0, 102, 153));
        jLabelEmpleado.setText("MATRICULA");
        getContentPane().add(jLabelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 60));

        jLSemestre.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLSemestre.setText("SEMESTRE:");
        getContentPane().add(jLSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabelanio.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabelanio.setText("AÑO:");
        getContentPane().add(jLabelanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLCliclo.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLCliclo.setText("CICLO:");
        getContentPane().add(jLCliclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabeljornada.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabeljornada.setText("JORNADA:");
        getContentPane().add(jLabeljornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        jCCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basico", "Avanzado" }));
        jCCiclo.setSelectedIndex(-1);
        jCCiclo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCCicloItemStateChanged(evt);
            }
        });
        getContentPane().add(jCCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 90, -1));

        jLnombre.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLnombre.setForeground(new java.awt.Color(0, 0, 51));
        getContentPane().add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 290, 29));

        jBAgregar4.setBackground(new java.awt.Color(0, 0, 0));
        jBAgregar4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jBAgregar4.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar4.setText("AGREGAR");
        jBAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregar4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBAgregar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));

        jCSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jCSemestre.setSelectedIndex(-1);
        jCSemestre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCSemestreItemStateChanged(evt);
            }
        });
        getContentPane().add(jCSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, -1));

        jBEditar.setBackground(new java.awt.Color(0, 0, 0));
        jBEditar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jBEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBEditar.setText("EDITAR");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 80, -1));

        jCAnioMtr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1995", "1996", "1997", "1998", "1999" }));
        jCAnioMtr.setSelectedIndex(-1);
        jCAnioMtr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCAnioMtrItemStateChanged(evt);
            }
        });
        jCAnioMtr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCAnioMtrKeyTyped(evt);
            }
        });
        getContentPane().add(jCAnioMtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 70, -1));

        jCJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diurna", "Nocturna" }));
        jCJornada.setSelectedIndex(-1);
        jCJornada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCJornadaItemStateChanged(evt);
            }
        });
        getContentPane().add(jCJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 90, -1));

        jBNext.setBackground(new java.awt.Color(0, 0, 0));
        jBNext.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jBNext.setForeground(new java.awt.Color(255, 255, 255));
        jBNext.setText("CONTINUAR");
        jBNext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBNextFocusGained(evt);
            }
        });
        jBNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBNextMousePressed(evt);
            }
        });
        jBNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNextActionPerformed(evt);
            }
        });
        jBNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jBNextKeyTyped(evt);
            }
        });
        getContentPane().add(jBNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jBsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/closei.png"))); // NOI18N
        jBsalir.setBorder(null);
        jBsalir.setBorderPainted(false);
        jBsalir.setContentAreaFilled(false);
        jBsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 9, 30, 20));

        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abstracto-azul.jpg"))); // NOI18N
        jLfondo.setText("jLabel1");
        jLfondo.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 5, 10, 5, new javax.swing.ImageIcon(getClass().getResource("/imagenes/blakw.png")))); // NOI18N
        getContentPane().add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 455, 300));

        jLIdEstudiant.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLIdEstudiant.setForeground(new java.awt.Color(0, 0, 51));
        jLIdEstudiant.setText("CODIGO");
        getContentPane().add(jLIdEstudiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 28));
        getContentPane().add(jTIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 10, 20));
        getContentPane().add(JIdestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregar4ActionPerformed

        aMatriculas dts = new aMatriculas();
        Fmatriculas func = new Fmatriculas();
        func.Mostrar(dts);

        //se valida que se llenen los datos        
        if (jCAnioMtr.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, " debe ingresar el año de la matricula");
            jCAnioMtr.requestFocus();
            return;
        }

        if (jCSemestre.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, " debe ingresar el semestre de matricula");
            jCSemestre.requestFocus();
            return;
        }

        if (jCJornada.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, " debe ingresar la jornada de matricula");
            jCJornada.requestFocus();
            return;
        }

        if (jCCiclo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, " debe ingresar el ciclo de la matricula");
            jCCiclo.requestFocus();
            return;
        }

        // capturar los datos 
        dts.setIdEstudiante(Integer.parseInt(Formestu.idestudiante));
        dts.setAniomatr(jCAnioMtr.getSelectedItem().toString().trim());
        dts.setSemestre(jCSemestre.getSelectedItem().toString().trim());
        dts.setJornada(jCJornada.getSelectedItem().toString().trim());
        dts.setCiclo(jCCiclo.getSelectedItem().toString().trim());
        dts.setIdmatricula(IdMatricula);

        if (func.insertar(dts)) {
            JOptionPane.showMessageDialog(null, "matricula creado con exito");

            Deshabilitar();
            jBNext.setEnabled(true);
            jCJornada.requestFocus();
        }

    }//GEN-LAST:event_jBAgregar4ActionPerformed

    private void jBNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNextActionPerformed

        Formnotas form = new Formnotas();
        Escritorio.add(form);
        Dimension desktopSize = Escritorio.getSize();
        Dimension FrameSize = form.getSize();
        form.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        form.show();
        this.setVisible(false);

        aMatriculas dts = new aMatriculas();
        Fmatriculas func = new Fmatriculas();
        func.Mostrar(dts);
        Formnotas.jLSemestre.setText("SEMESTRE: " + jCSemestre.getSelectedItem().toString());
        Formnotas.jLAnio.setText("AÑO: " + jCAnioMtr.getSelectedItem().toString());
        Formnotas.jLJornada.setText("JORNADA: " + jCJornada.getSelectedItem().toString());
        Formnotas.jLCiclo.setText("CICLO: " + jCCiclo.getSelectedItem().toString());
        String ciclo = Integer.toString(jCCiclo.getSelectedIndex() + 1);
        Formnotas.JTciclo.setText(ciclo);
        anio = jCAnioMtr.getSelectedItem().toString();
        semes = jCSemestre.getSelectedItem().toString();
        jornada = jCJornada.getSelectedItem().toString();
        cicl = jCCiclo.getSelectedItem().toString();
        IdMatricula = dts.getIdmatricula();

        if (cicl.equals("Basico")) {
            Formnotas.jLaMat1.setText("Matematicas");
            Formnotas.jLaMat2.setText("Ciencias Sociales");
            Formnotas.jLaMat3.setText("Ciencias Naturales");
            Formnotas.jLaMat4.setText("Español");
            Formnotas.jLaMat5.setText("Ingles");
            Formnotas.jLaMat6.setText("Artes");

        } else {
            Formnotas.jLaMat1.setText("Matematicas II");
            Formnotas.jLaMat2.setText("Ciencias Sociales II");
            Formnotas.jLaMat3.setText("Ciencias Naturales II");
            Formnotas.jLaMat4.setText("Español II");
            Formnotas.jLaMat5.setText("Ingles II");
            Formnotas.jLaMat6.setText("Desarrollo Personal");

        }

    }//GEN-LAST:event_jBNextActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        check();

    }//GEN-LAST:event_jBEditarActionPerformed

    private void jCAnioMtrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCAnioMtrItemStateChanged
        check();
    }//GEN-LAST:event_jCAnioMtrItemStateChanged

    private void jCSemestreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCSemestreItemStateChanged
        check();

    }//GEN-LAST:event_jCSemestreItemStateChanged

    private void jBNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBNextMousePressed
        aMatriculas dts = new aMatriculas();
        Fmatriculas func = new Fmatriculas();
        func.Mostrar(dts);
        anio = jCAnioMtr.getSelectedItem().toString();
        semes = jCSemestre.getSelectedItem().toString();
        jornada = jCJornada.getSelectedItem().toString();
        cicl = jCCiclo.getSelectedItem().toString();
        IdMatricula = dts.getIdmatricula();

    }//GEN-LAST:event_jBNextMousePressed

    private void jBNextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBNextFocusGained
        aMatriculas dts = new aMatriculas();
        Fmatriculas func = new Fmatriculas();
        func.Mostrar(dts);
        anio = jCAnioMtr.getSelectedItem().toString();
        semes = jCSemestre.getSelectedItem().toString();
        jornada = jCJornada.getSelectedItem().toString();
        cicl = jCCiclo.getSelectedItem().toString();
        IdMatricula = dts.getIdmatricula();
    }//GEN-LAST:event_jBNextFocusGained

    private void jCAnioMtrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCAnioMtrKeyTyped
        char cTeclaPresionada = evt.getKeyChar();
        if (cTeclaPresionada == KeyEvent.VK_ENTER) {
            jBNext.doClick();
        }
    }//GEN-LAST:event_jCAnioMtrKeyTyped

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

        if (jCCiclo.getSelectedIndex() != -1) {
            jBNext.requestFocus();
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void jBNextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBNextKeyTyped
        char cTeclaPresionada = evt.getKeyChar();
        if (cTeclaPresionada == KeyEvent.VK_ENTER) {
            jBNext.doClick();
        }
    }//GEN-LAST:event_jBNextKeyTyped

    private void jCJornadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCJornadaItemStateChanged
        if (jCCiclo.getSelectedIndex() != -1
                && jCJornada.getSelectedIndex() != -1) {
            jBAgregar4.setEnabled(true);
        }
    }//GEN-LAST:event_jCJornadaItemStateChanged

    private void jCCicloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCCicloItemStateChanged
        if (jCCiclo.getSelectedIndex() != -1
                && jCJornada.getSelectedIndex() != -1) {
            jBAgregar4.setEnabled(true);
        }
    }//GEN-LAST:event_jCCicloItemStateChanged

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        dupl = 0;
    }//GEN-LAST:event_formInternalFrameClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formmtric.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formmtric.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formmtric.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formmtric.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formmtric().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel JIdestudiante;
    private javax.swing.JButton jBAgregar4;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBNext;
    private javax.swing.JButton jBsalir;
    public static javax.swing.JComboBox<String> jCAnioMtr;
    public static javax.swing.JComboBox<String> jCCiclo;
    public static javax.swing.JComboBox<String> jCJornada;
    public static javax.swing.JComboBox<String> jCSemestre;
    private javax.swing.JLabel jLCliclo;
    public static javax.swing.JLabel jLIdEstudiant;
    private javax.swing.JLabel jLSemestre;
    private javax.swing.JLabel jLabelEmpleado;
    private javax.swing.JLabel jLabelanio;
    private javax.swing.JLabel jLabeljornada;
    public static javax.swing.JLabel jLfondo;
    public static javax.swing.JLabel jLnombre;
    public static javax.swing.JTextField jTIdEstudiante;
    // End of variables declaration//GEN-END:variables

    //public static void estudiante(String estudiante) {
    //       idestudiante = estudiante;
    // }
}
